# Generated by Django 3.2.5 on 2021-09-04 10:01

from django.db import migrations, models
import tenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=tenant.models.get_client_logo_folder),
        ),
    ]
