# Generated by Django 3.2.5 on 2021-07-31 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_rename_templates_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='data_sheet',
            field=models.FileField(default=None, upload_to='data_sheets/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
