# Generated by Django 3.2.5 on 2021-08-14 13:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20210813_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2021, 8, 14, 19, 17, 12, 997694), help_text='Datetime on which this record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True),
        ),
        migrations.AddField(
            model_name='datakey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datakey_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datakey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2021, 8, 14, 19, 17, 25, 601090), help_text='Datetime on which this record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datakey',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datakey',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datakey_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datakey',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasheet_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2021, 8, 14, 19, 17, 39, 974613), help_text='Datetime on which this record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasheet_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2021, 8, 14, 19, 17, 53, 610908), help_text='Datetime on which this record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
