# Generated by Django 3.2.5 on 2021-07-31 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_auto_20210731_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime on which this record was created.')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='template',
            name='created_by',
        ),
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.ManyToManyField(related_name='templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='template',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='template',
            name='updated_by',
            field=models.ManyToManyField(null=True, related_name='templates_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime on which this record was created.')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True)),
                ('file', models.FileField(upload_to='certificates/%Y/%m/%d/')),
                ('created_by', models.ManyToManyField(related_name='certificate_created', to='services.Template')),
                ('data_keys', models.ManyToManyField(related_name='certificates', to='services.DataKey')),
                ('updated_by', models.ManyToManyField(null=True, related_name='certificate_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
