# Generated by Django 3.2.5 on 2021-08-18 06:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210814_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='template',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=None, null=True, size=None),
        ),
    ]
