# Generated by Django 3.2.5 on 2021-07-31 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_auto_20210731_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='created_by',
        ),
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
