# Generated by Django 3.2.5 on 2021-07-31 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_auto_20210731_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_created', to='services.template'),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='data_keys',
        ),
        migrations.AddField(
            model_name='certificate',
            name='data_keys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='services.datakey'),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='template',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='template',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
