# Generated by Django 3.2.5 on 2021-08-19 11:14

from django.db import migrations
from django.db import models, migrations
import services.utilities as utl


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=utl.Groups.issuer),
        Group(name=utl.Groups.awardee),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'Generator',
            u'Awardee',
        ]
    ).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210818_2010'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
