# Generated by Django 3.2.5 on 2021-07-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210731_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='data_sheet',
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime on which this record was created.')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('data_sheet', models.FileField(upload_to='data_sheets/%Y/%m/%d/')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sheet', to='services.template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
