# Generated by Django 3.2.5 on 2021-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210731_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='batch_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
