# Generated by Django 3.2.5 on 2021-08-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210819_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='file_jpg',
            field=models.FileField(blank=True, null=True, upload_to='templates/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='services.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='awardee_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
