# Generated by Django 3.2.5 on 2021-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_certificate_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='data_keys',
        ),
        migrations.AddField(
            model_name='certificate',
            name='data_keys',
            field=models.ManyToManyField(null=True, related_name='certificates', to='services.DataKey'),
        ),
    ]
