# Generated by Django 3.2.5 on 2021-08-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210820_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='file_jpg',
        ),
    ]
