# Generated by Django 3.2.5 on 2021-08-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_template_file_jpg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
