# Generated by Django 3.2.5 on 2021-07-31 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_auto_20210731_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='services.template'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
