# Generated by Django 3.2.5 on 2021-07-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210731_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='updated_by',
        ),
    ]
