# Generated by Django 3.2.5 on 2021-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='awardee',
        ),
        migrations.AddField(
            model_name='certificate',
            name='awardee_public_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
