# Generated by Django 3.2.5 on 2021-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_certificate_awardee_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('UN', 'Unpublished'), ('PB', 'Published')], default='UN', max_length=2),
        ),
    ]
