# Generated by Django 3.2.5 on 2021-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_template_file_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file_thumbnail',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='templates/thumbnails/%Y/%m/%d/'),
        ),
    ]
