# Generated by Django 3.2.5 on 2021-09-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_template_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='public_certificate_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
