# Generated by Django 3.2.5 on 2021-09-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210831_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
