# Generated by Django 3.2.5 on 2021-08-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime on which this record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Datetime on which this record was last modified.', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_name', models.CharField(max_length=128)),
                ('sms_available', models.BooleanField(default=False)),
                ('email_available', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='certificates/%Y/%m/%d/')),
                ('tenant_schema_name', models.CharField(max_length=128)),
                ('tenant_awarded_by_user_id', models.BigIntegerField()),
                ('tenant_event_id', models.BigIntegerField()),
                ('awardee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_certificates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publiccertificate_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publiccertificate_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
