# Generated by Django 3.2.5 on 2021-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_publicprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiccertificate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='publiccertificate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='publicprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='publicprofile',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='publiccertificate',
            name='tenant_created_by_user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publiccertificate',
            name='tenant_updated_by_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='tenant_created_by_user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='tenant_schema_name',
            field=models.CharField(default='public', max_length=128),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='tenant_updated_by_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
