# Generated by Django 3.2.5 on 2021-08-31 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0004_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicProfile',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='publiccertificate',
            name='tenant_awarded_by_user_id',
        ),
        migrations.RemoveField(
            model_name='publiccertificate',
            name='tenant_event_id',
        ),
        migrations.AlterField(
            model_name='publiccertificate',
            name='tenant_schema_name',
            field=models.CharField(default='public', max_length=128),
        ),
    ]
