# Generated by Django 3.2.5 on 2021-08-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20210831_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
