# Generated by Django 3.2.5 on 2021-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccertificate',
            name='tenant_awarded_by_user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publiccertificate',
            name='tenant_event_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
