# Generated by Django 3.2.5 on 2021-09-01 01:52

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_public_user_id'),
        ('public', '0007_auto_20210831_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
