# Generated by Django 3.2.5 on 2021-09-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_publicuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccertificate',
            name='awardee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_certificates', to='public.publicuser'),
        ),
    ]
