# Generated by Django 3.2.5 on 2021-09-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_freetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccertificate',
            name='download_by_awardee_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='publiccertificate',
            name='download_by_public_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
